In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data.csv', encoding = 'ISO-8859-1')

In [4]:
df.shape

(541909, 8)

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [8]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [9]:
for column in df.columns:
    print(column)

InvoiceNo
StockCode
Description
Quantity
InvoiceDate
UnitPrice
CustomerID
Country

In [11]:
d = {
        'InvoiceNo': 'invoice_num',
        'StockCode' : 'stock_code',
        'Description' : 'description',
        'Quantity' : 'quantity',
        'InvoiceDate' : 'invoice_date',
        'UnitPrice' : 'unit_price',
        'CustomerID' : 'cust_id',
        'Country' : 'country'
}

In [12]:
d

{'InvoiceNo': 'invoice_num',
 'StockCode': 'stock_code',
 'Description': 'description',
 'Quantity': 'quantity',
 'InvoiceDate': 'invoice_date',
 'UnitPrice': 'unit_price',
 'CustomerID': 'cust_id',
 'Country': 'country'}

In [13]:
df.rename(columns = d, inplace = True)

In [14]:
df.columns

Index(['invoice_num', 'stock_code', 'description', 'quantity', 'invoice_date',
       'unit_price', 'cust_id', 'country'],
      dtype='str')

In [15]:
for i in df.columns:
    print(i)

invoice_num
stock_code
description
quantity
invoice_date
unit_price
cust_id
country

In [16]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [17]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [18]:
df.dtypes

invoice_num         str
stock_code          str
description         str
quantity          int64
invoice_date        str
unit_price      float64
cust_id         float64
country             str
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   541909 non-null  str
 1   stock_code    541909 non-null  str
 2   description   540455 non-null  str
 3   quantity      541909 non-null  int64
 4   invoice_date  541909 non-null  str
 5   unit_price    541909 non-null  float64
 6   cust_id       406829 non-null  float64
 7   country       541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 67.3 MB

In [20]:
df.isnull()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
541904,False,False,False,False,False,False,False,False
541905,False,False,False,False,False,False,False,False
541906,False,False,False,False,False,False,False,False
541907,False,False,False,False,False,False,False,False
541908,False,False,False,False,False,False,False,False

In [21]:
len(df.columns)

8

In [22]:
df.shape

(541909, 8)

In [23]:
df.isnull().sum()

invoice_num          0
stock_code           0
description       1454
quantity             0
invoice_date         0
unit_price           0
cust_id         135080
country              0
dtype: int64

In [24]:
df.isnull().sum().sort_values()

invoice_num          0
stock_code           0
quantity             0
invoice_date         0
country              0
unit_price           0
description       1454
cust_id         135080
dtype: int64

In [25]:
df.isnull().sum().sort_values(ascending = False)

cust_id         135080
description       1454
stock_code           0
invoice_num          0
quantity             0
invoice_date         0
unit_price           0
country              0
dtype: int64

In [26]:
df.dtypes

invoice_num         str
stock_code          str
description         str
quantity          int64
invoice_date        str
unit_price      float64
cust_id         float64
country             str
dtype: object

In [27]:
df.head(2)

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [28]:
df['invoice_date'] = pd.to_datetime(df.invoice_date, format='%m/%d/%Y %H:%M')

In [29]:
df.dtypes

invoice_num                str
stock_code                 str
description                str
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
cust_id                float64
country                    str
dtype: object

In [30]:
df.description

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541904            PACK OF 20 SPACEBOY NAPKINS
541905           CHILDREN'S APRON DOLLY GIRL
541906          CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908          BAKING SET 9 PIECE RETROSPOT
Name: description, Length: 541909, dtype: str

In [31]:
df.description.str.lower()

0          white hanging heart t-light holder
1                         white metal lantern
2              cream cupid hearts coat hanger
3         knitted union flag hot water bottle
4              red woolly hottie white heart.
                         ...
541904            pack of 20 spaceboy napkins
541905           children's apron dolly girl
541906          childrens cutlery dolly girl
541907        childrens cutlery circus parade
541908          baking set 9 piece retrospot
Name: description, Length: 541909, dtype: str

In [32]:
df.head(3)

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom

In [33]:
df['description'] = df.description.str.lower()

In [34]:
df.isnull().sum().sort_values(ascending = False)

cust_id         135080
description       1454
stock_code           0
invoice_num          0
quantity             0
invoice_date         0
unit_price           0
country              0
dtype: int64

In [36]:
df_new = df.dropna()

In [37]:
df_new.isnull().sum()

invoice_num     0
stock_code      0
description     0
quantity        0
invoice_date    0
unit_price      0
cust_id         0
country         0
dtype: int64

In [38]:
df_new.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   406829 non-null  str
 1   stock_code    406829 non-null  str
 2   description   406829 non-null  str
 3   quantity      406829 non-null  int64
 4   invoice_date  406829 non-null  datetime64[us]
 5   unit_price    406829 non-null  float64
 6   cust_id       406829 non-null  float64
 7   country       406829 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 47.9 MB

In [39]:
df_new.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   406829 non-null  str
 1   stock_code    406829 non-null  str
 2   description   406829 non-null  str
 3   quantity      406829 non-null  int64
 4   invoice_date  406829 non-null  datetime64[us]
 5   unit_price    406829 non-null  float64
 6   cust_id       406829 non-null  float64
 7   country       406829 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 47.9 MB

In [40]:
df_new.dtypes

invoice_num                str
stock_code                 str
description                str
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
cust_id                float64
country                    str
dtype: object

In [41]:
df_new['cust_id']

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: cust_id, Length: 406829, dtype: float64

In [42]:
import warnings
warnings.filterwarnings('ignore')

In [43]:
df_new['cust_id'] = df_new['cust_id'].astype('int64')

In [44]:
df_new.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [45]:
df_new.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   406829 non-null  str
 1   stock_code    406829 non-null  str
 2   description   406829 non-null  str
 3   quantity      406829 non-null  int64
 4   invoice_date  406829 non-null  datetime64[us]
 5   unit_price    406829 non-null  float64
 6   cust_id       406829 non-null  int64
 7   country       406829 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 47.9 MB

In [46]:
df_new.describe()

            quantity                invoice_date     unit_price        cust_id
count  406829.000000                      406829  406829.000000  406829.000000
mean       12.061303  2011-07-10 16:30:57.879207       3.460471   15287.690570
min    -80995.000000         2010-12-01 08:26:00       0.000000   12346.000000
25%         2.000000         2011-04-06 15:02:00       1.250000   13953.000000
50%         5.000000         2011-07-31 11:48:00       1.950000   15152.000000
75%        12.000000         2011-10-20 13:06:00       3.750000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       248.693370                         NaN      69.315162    1713.600303

In [47]:
df_new.describe().round(2)

        quantity                invoice_date  unit_price    cust_id
count  406829.00                      406829   406829.00  406829.00
mean       12.06  2011-07-10 16:30:57.879207        3.46   15287.69
min    -80995.00         2010-12-01 08:26:00        0.00   12346.00
25%         2.00         2011-04-06 15:02:00        1.25   13953.00
50%         5.00         2011-07-31 11:48:00        1.95   15152.00
75%        12.00         2011-10-20 13:06:00        3.75   16791.00
max     80995.00         2011-12-09 12:50:00    38970.00   18287.00
std       248.69                         NaN       69.32    1713.60

In [48]:
values = [1, 2, 3, -4, -5, 6, 7]

In [49]:
for value in values:
    print(value)

1
2
3
-4
-5
6
7

In [50]:
for value in values:
    if value >= 0:
        print(value)

1
2
3
6
7

In [51]:
df_new.quantity > 0

0         True
1         True
2         True
3         True
4         True
          ...
541904    True
541905    True
541906    True
541907    True
541908    True
Name: quantity, Length: 406829, dtype: bool

In [52]:
con = df_new.quantity > 0

In [53]:
df_new = df_new[con]

In [54]:
df_new.describe().round(2)

        quantity                invoice_date  unit_price    cust_id
count  397924.00                      397924   397924.00  397924.00
mean       13.02  2011-07-10 23:43:36.912476        3.12   15294.32
min         1.00         2010-12-01 08:26:00        0.00   12346.00
25%         2.00         2011-04-07 11:12:00        1.25   13969.00
50%         6.00         2011-07-31 14:39:00        1.95   15159.00
75%        12.00         2011-10-20 14:33:00        3.75   16795.00
max     80995.00         2011-12-09 12:50:00     8142.75   18287.00
std       180.42                         NaN       22.10    1713.17

In [55]:
df_new.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [56]:
df_new.shape

(397924, 8)

In [57]:
df_new['amount_spent'] = df_new['quantity'] * df_new['unit_price']

In [58]:
df_new.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,cust_id,country,amount_spent
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [59]:
for col in df_new.columns:
    print(col)

invoice_num
stock_code
description
quantity
invoice_date
unit_price
cust_id
country
amount_spent

In [60]:
col_order = ['invoice_num','invoice_date','stock_code','description','quantity','unit_price','amount_spent','cust_id','country']

In [61]:
df_new = df_new[col_order]

In [62]:
df_new.head()

,invoice_num,invoice_date,stock_code,description,quantity,unit_price,amount_spent,cust_id,country
0,536365,2010-12-01 08:26:00,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

In [63]:
df_new.shape

(397924, 9)

In [64]:
len(df_new.columns)

9

In [65]:
df_new['invoice_date']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: invoice_date, Length: 397924, dtype: datetime64[us]

In [66]:
df_new.invoice_date

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: invoice_date, Length: 397924, dtype: datetime64[us]

In [67]:
df_new['invoice_date'].dt.year

0         2010
1         2010
2         2010
3         2010
4         2010
          ...
541904    2011
541905    2011
541906    2011
541907    2011
541908    2011
Name: invoice_date, Length: 397924, dtype: int32

In [68]:
df_new['invoice_date'].dt.month

0         12
1         12
2         12
3         12
4         12
          ..
541904    12
541905    12
541906    12
541907    12
541908    12
Name: invoice_date, Length: 397924, dtype: int32

In [69]:
df_new.head(2)

,invoice_num,invoice_date,stock_code,description,quantity,unit_price,amount_spent,cust_id,country
0,536365,2010-12-01 08:26:00,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom